-- MySQL Script generated by MySQL Workbench
-- dimecres, 17 de novembre de 2021, 17:21:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spotify
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spotify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spotify` ;
USE `spotify` ;

-- -----------------------------------------------------
-- Table `spotify`.`usuari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`usuari` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `data_neixement` DATE NULL,
  `sexe` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `cp` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`subscripcio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`subscripcio` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_inici` DATETIME NOT NULL,
  `data_renovacio` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`premium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`premium` (
  `id_usuari` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_usuari`),
  CONSTRAINT `fk_premium_1`
    FOREIGN KEY (`id_usuari`)
    REFERENCES `spotify`.`usuari` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`forma_pagament`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`forma_pagament` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuari` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_forma_pagament_1_idx` (`id_usuari` ASC) VISIBLE,
  CONSTRAINT `fk_forma_pagament_1`
    FOREIGN KEY (`id_usuari`)
    REFERENCES `spotify`.`premium` (`id_usuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`tarjeta` (
  `id_forma_pagament` INT UNSIGNED NOT NULL,
  `num` VARCHAR(25) NOT NULL,
  `mes` VARCHAR(2) NULL,
  `any` VARCHAR(2) NULL,
  `codi` VARCHAR(3) NULL,
  PRIMARY KEY (`id_forma_pagament`),
  INDEX `fk_tarjeta_1_idx` (`id_forma_pagament` ASC) VISIBLE,
  CONSTRAINT `fk_tarjeta_1`
    FOREIGN KEY (`id_forma_pagament`)
    REFERENCES `spotify`.`forma_pagament` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`paypal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`paypal` (
  `id_forma_pagament` INT UNSIGNED NOT NULL,
  `username` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_forma_pagament`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_paypal_1`
    FOREIGN KEY (`id_forma_pagament`)
    REFERENCES `spotify`.`forma_pagament` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`pagament`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`pagament` (
  `num_ordre` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `total` DOUBLE NOT NULL,
  `id_usuari` INT UNSIGNED NOT NULL,
  `id_subscripcio` INT UNSIGNED NOT NULL,
  `id_forma_pagament` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`num_ordre`, `id_usuari`, `id_subscripcio`, `id_forma_pagament`),
  INDEX `fk_pagament_2_idx` (`id_subscripcio` ASC) VISIBLE,
  INDEX `fk_pagament_1_idx` (`id_usuari` ASC) VISIBLE,
  INDEX `fk_pagament_3_idx` (`id_forma_pagament` ASC) VISIBLE,
  CONSTRAINT `fk_pagament_1`
    FOREIGN KEY (`id_usuari`)
    REFERENCES `spotify`.`premium` (`id_usuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagament_2`
    FOREIGN KEY (`id_subscripcio`)
    REFERENCES `spotify`.`subscripcio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagament_3`
    FOREIGN KEY (`id_forma_pagament`)
    REFERENCES `spotify`.`forma_pagament` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`playlist` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titol` VARCHAR(45) NOT NULL,
  `n_cancons` INT UNSIGNED NOT NULL,
  `data_creacio` DATETIME NOT NULL,
  `data_esborrat` DATETIME NULL,
  `pertany` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_playlist_1_idx` (`pertany` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_1`
    FOREIGN KEY (`pertany`)
    REFERENCES `spotify`.`usuari` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`comparticio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`comparticio` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_playlist` INT UNSIGNED NOT NULL,
  `id_usuari` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_playlist`, `id_usuari`),
  INDEX `fk_comparticio_2_idx` (`id_playlist` ASC) VISIBLE,
  INDEX `fk_comparticio_1_idx` (`id_usuari` ASC) VISIBLE,
  CONSTRAINT `fk_comparticio_1`
    FOREIGN KEY (`id_usuari`)
    REFERENCES `spotify`.`usuari` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comparticio_2`
    FOREIGN KEY (`id_playlist`)
    REFERENCES `spotify`.`playlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`artista` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `imatge` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`album` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titol` VARCHAR(45) NOT NULL,
  `any` VARCHAR(4) NULL,
  `imatge` VARCHAR(255) NULL,
  `id_artista` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_album_1_idx` (`id_artista` ASC) VISIBLE,
  CONSTRAINT `fk_album_1`
    FOREIGN KEY (`id_artista`)
    REFERENCES `spotify`.`artista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`canco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`canco` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titol` VARCHAR(45) NOT NULL,
  `durada_seg` INT UNSIGNED NULL,
  `n_reproduccions` INT UNSIGNED NOT NULL,
  `id_album` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_canco_1_idx` (`id_album` ASC) VISIBLE,
  CONSTRAINT `fk_canco_1`
    FOREIGN KEY (`id_album`)
    REFERENCES `spotify`.`album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`afegiment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`afegiment` (
  `id_comparticio` INT UNSIGNED NOT NULL,
  `id_canco` INT UNSIGNED NOT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`id_comparticio`, `id_canco`),
  INDEX `fk_afegiment_2_idx` (`id_canco` ASC) VISIBLE,
  CONSTRAINT `fk_afegiment_1`
    FOREIGN KEY (`id_comparticio`)
    REFERENCES `spotify`.`comparticio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_afegiment_2`
    FOREIGN KEY (`id_canco`)
    REFERENCES `spotify`.`canco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`seguiment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`seguiment` (
  `id_usuari` INT UNSIGNED NOT NULL,
  `id_artista` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_usuari`, `id_artista`),
  INDEX `fk_seguiment_2_idx` (`id_artista` ASC) VISIBLE,
  CONSTRAINT `fk_seguiment_1`
    FOREIGN KEY (`id_usuari`)
    REFERENCES `spotify`.`usuari` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seguiment_2`
    FOREIGN KEY (`id_artista`)
    REFERENCES `spotify`.`artista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`relacio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`relacio` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`relacionat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`relacionat` (
  `id_relacio` INT UNSIGNED NOT NULL,
  `id_artista` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_relacio`, `id_artista`),
  CONSTRAINT `fk_relacionat_1`
    FOREIGN KEY (`id_artista`)
    REFERENCES `spotify`.`artista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relacionat_2`
    FOREIGN KEY (`id_relacio`)
    REFERENCES `spotify`.`relacio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`album_favorit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`album_favorit` (
  `id_usuari` INT UNSIGNED NOT NULL,
  `id_album` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_usuari`, `id_album`),
  INDEX `fk_album_favorit_2_idx` (`id_album` ASC) VISIBLE,
  CONSTRAINT `fk_album_favorit_1`
    FOREIGN KEY (`id_usuari`)
    REFERENCES `spotify`.`usuari` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_album_favorit_2`
    FOREIGN KEY (`id_album`)
    REFERENCES `spotify`.`album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify`.`canco_favorita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`canco_favorita` (
  `id_usuari` INT UNSIGNED NOT NULL,
  `id_canco` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_usuari`, `id_canco`),
  INDEX `fk_canco_favorita_2_idx` (`id_canco` ASC) VISIBLE,
  CONSTRAINT `fk_canco_favorita_1`
    FOREIGN KEY (`id_usuari`)
    REFERENCES `spotify`.`usuari` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_canco_favorita_2`
    FOREIGN KEY (`id_canco`)
    REFERENCES `spotify`.`canco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
